version: "2"
services:

  selv-v3-report:
    image: openlmismz/selv-v3-report
    links:
      - db
      - log
    env_file: .env

  db:
    image: openlmis/postgres:9.6
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:514"
        syslog-facility: "local1"
    depends_on: [log]
    env_file: .env

  log:
    image: openlmis/rsyslog:1
    ports:
      - "514:514"
    volumes:
      - '../logs/report:/var/log'
